### ISSUE TITLE
nodenv: nodemon: command not found

### ISSUE THREAD

**Issue by dawnerd** [nodenv/nodenv#138]
```
$ node --version
v10.16.0

$ npm install -g nodemon
/usr/local/bin/nodemon -> /usr/local/lib/node_modules/nodemon/bin/nodemon.js

> nodemon@1.19.1 postinstall /usr/local/lib/node_modules/nodemon
> node bin/postinstall || exit 0

+ nodemon@1.19.1
updated 1 package in 2.984s

$ nodenv rehash

$ nodemon
nodenv: nodemon: command not found

The `nodemon' command exists in these Node versions:
  8.8.0
```

Updated from brew: nodenv 1.3.0

Kind of out of ideas here. Tried using node 10.10 as well, same result.

**Comment by fibric** [comment]
I can't confirm. On my machine `nodemon` is installable.

```$ nodenv install 10.16.0```
```$ nodenv local 10.16.0```
```
$ npm -v
6.10.0
```
```
$ npm i -g nodemon
nodemon@1.19.1
added 289 packages from 144 contributors in 12.654s
```
```$ nodenv rehash```
```
$ nodemon
[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/Users/fibric/Download/test/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[nodemon] app crashed - waiting for file changes before starting...
^C⏎```

**Comment by dawnerd** [comment]
It must have been an issue with that version of node, 8.8.0. Uninstalled it and now it works.
